# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.vetjc.com
title: Vet JC 
email: jcmrcvs@gmail.com.com
author: Jonathan Cranston
description: Cotswold Freelance Veterinary Surgeon.
  
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    url: mailto:jmrcvs@gmail.com
  - title: linkedin
    url: https://uk.linkedin.com/pub/jonathan-cranston/31/ba/351
  - title: instagram
    url: https://instagram.com/the_cotswold_vet/
